{
 "title": "Apm Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime by HostName ($Dimension)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": " Hostname:  {{Hostname}}, Application: {{AppserverType}}",
     "metric": "Uptime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "Uptime[5m]{$dimension}.count()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Thread Waiting, Dead Lock Count ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Count ",
     "metric": "ThreadCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadCount[1m]{$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Waiting Count",
     "metric": "ThreadWaitingCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadWaitingCount[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Deadlock Count",
     "metric": "ThreadDeadlockCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadDeadlockCount[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU process Load {Dimension}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "Hostname:  {{HostNames}}, Apllication:  {{AppserverType}} ",
     "metric": "ProcessCpuLoad",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ProcessCpuLoad[5m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Process Time {Dimension}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Hostname:  {{HostNames}}, Apllication:  {{AppserverType}} ",
     "metric": "ProcessCpuTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ProcessCpuTime[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Heap Commited and Heap Used for a given Host",
   "type": "stat",
   "description": "This chart shows how much heap memory is committed versus how much is actually used over time. It helps in understanding the efficiency of memory usage and identifying potential memory issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Committed  ",
     "metric": "HeapCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "HeapCommitted[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Used ",
     "metric": "HeapUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "HeapUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Committed GC After Old v After Young  for a given Host",
   "type": "stat",
   "description": "Current committed memory for both old and young generations, which is useful for real-time monitoring.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Old Committed",
     "metric": "GcAfterOldCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterOldCommitted[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Young Committed ",
     "metric": "GcAfterYoungCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterYoungCommitted[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Used GC After Old v After Young for a given Host",
   "type": "timeseries",
   "description": "Shows how much memory is being used after each GC event. A gradual increase in memory usage can indicate a memory leak.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Old Used {{HostNames}}",
     "metric": "GcAfterOldUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterOldUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Young Used {{HostNames}}",
     "metric": "GcAfterYoungUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterYoungUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total Time GC Young v Old Total for a given Hostname",
   "type": "timeseries",
   "description": "Track how often garbage collection is happening (both young and old generations) Track how much time is being spent on garbage collection (both young and old generations). Long GC times can indicate performance issues.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC Young Total  - {{HostNames}}",
     "metric": "GcYoungTotalTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcYoungTotalTime[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC Old Total - {{HostNames}}",
     "metric": "GcOldTotalTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcOldTotalTime[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}